#!name=Locket Gold 🏅- NightmarketServer
#!desc=Mở khoá premium cho ứng dụng Locket Widget 
#!author=NightmarketServer

[MITM]
hostname = api.revenuecat.com

[Script]
Locket Gold (Server Weishi) = type=http-response, pattern=^https:\/\/api\.revenuecat\.com\/.+\/(receipts$|subscribers\/[^/]+$), requires-body=1, max-size=0, script-path=https://raw.githubusercontent.com/NightmarketServer/Locket/refs/heads/main/Locket.js, update-interval=5

[Header Rewrite]
^https?://api.revenuecat.com/.+/(receipts$|subscribers/?(.*?)*$) = delete header X-RevenueCat-ETag
^https?://api.revenuecat.com/.+/(receipts$|subscribers/?(.*?)*$) = delete header x-revenuecat-etag
