#!name=Locket Gold 🏅- NightmarketServer
#!desc=Mở khoá premium cho ứng dụng Locket Widget 
# 💬 Discord: https://discord.gg/juY9tw5AJY  
# 🚀 Rewrite by: Nightmarket Server  
# Author: William - Thành Long

[General]
bypass-system = true
skip-proxy = 192.168.0.0/16,10.0.0.0/8,172.16.0.0/12,localhost,*.local,captive.apple.com
tun-excluded-routes = 10.0.0.0/8,100.64.0.0/10,127.0.0.0/8,169.254.0.0/16,172.16.0.0/12,192.0.0.0/24,192.168.0.0/16,224.0.0.0/4,255.255.255.255/32
dns-server = https://doh.pub/dns-query,https://dns.alidns.com/dns-query,223.5.5.5,119.29.29.29
fallback-dns-server = system
ipv6 = false
prefer-ipv6 = false
dns-direct-system = false
icmp-auto-reply = true
always-reject-url-rewrite = false
private-ip-answer = true
udp-policy-not-supported-behaviour = REJECT
update-url = https://raw.githubusercontent.com/NightmarketServer/Locket/main/Locket.conf

[Rule]
# Final
FINAL,PROXY

[Host]
localhost = 127.0.0.1

[URL Rewrite]
^https?://(www.)?g.cn https://www.google.com 302
^https?://(www.)?google.cn https://www.google.com 302

# ~ Enhanced for Shadowrocket, Surge, & LanceX
revenuecat = type=http-response, pattern=^https:\/\/api\.revenuecat\.com\/.*\/(receipts$|subscribers\/[^/]+$), script-path=https://raw.githubusercontent.com/NightmarketServer/Locket/main/locketfix3.js, requires-body=true, max-size=-1, timeout=120
deleteHeader = type=http-request, pattern=^https:\/\/api\.revenuecat\.com\/.*\/(receipts|subscribers), script-path=https://raw.githubusercontent.com/NightmarketServer/Locket/main/header2.js, timeout=120

[MITM]
enable = true
hostname = api.revenuecat.com
