#!name=Locket Gold 🏅- NightmarketServer
#!desc=Mở khoá premium cho ứng dụng Locket Widget 
# 👤 Author: Nightmarket Server  
# 💬 Discord: https://discord.gg/juY9tw5AJY  
# 🚀 Released by: Nightmarket Server  
#!version=1.0.3

[Script]
http-response ^https:\/\/api\.revenuecat\.com\/v1\/subscribers\/ requires-body=1,script-path=https://raw.githubusercontent.com/NightmarketServer/Locket/refs/heads/main/Locket.js

[MITM]
hostname = api.revenuecat.com
