#!name=Locket Gold 🏅- NightmarketServer
#!desc=Mở khoá premium cho ứng dụng Locket Widget 
# 👤 Author: Dohungx - DEV Nightmarket 
# 💬 Discord: https://discord.gg/juY9tw5AJY  
# 🚀 Released by: Nightmarket Server  
#!version=1.0.3
update-url = https://raw.githubusercontent.com/NightmarketServer/Locket/refs/heads/main/locketV3.module

[Script]
# ~ By Dohungx - DEV Nightmarket
# ～ Egern transfer to Shadowrocket & Surge & LanceX
revenuecat = type=http-response, pattern=^https:\/\/api\.revenuecat\.com\/.+\/(receipts$|subscribers\/[^/]+$), script-path=https://raw.githubusercontent.com/dhungx/modules-shadowrocket/refs/heads/main/js/locket/Locket.js, requires-body=true, max-size=-1, timeout=60

deleteHeader = type=http-request, pattern=^https:\/\/api\.revenuecat\.com\/.+\/(receipts|subscribers), script-path=https://raw.githubusercontent.com/dhungx/modules-shadowrocket/refs/heads/main/js/locket/deleteHeader.js, timeout=60

[MITM]
hostname = %APPEND% api.revenuecat.com
